package me.sk.entity;
// Generated 2017-3-8 11:21:02 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Permissions generated by hbm2java
 */
@Entity
@Table(name = "permissions", catalog = "demo")
public class Permissions implements java.io.Serializable {

	private int permissionId;
	private String permission;
	private Set<Role> roleses = new HashSet<Role>(0);

	public Permissions() {
	}

	public Permissions(int permissionId, String permission) {
		this.permissionId = permissionId;
		this.permission = permission;
	}

	public Permissions(int permissionId, String permission, Set<Role> roleses) {
		this.permissionId = permissionId;
		this.permission = permission;
		this.roleses = roleses;
	}

	@Id

	@Column(name = "permissionId", unique = true, nullable = false)
	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "permission", nullable = false, length = 50)
	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "permissionses")
	public Set<Role> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Role> roleses) {
		this.roleses = roleses;
	}

}
