package me.sk.entity;
// Generated 2017-3-8 11:21:02 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "demo")
public class Role implements java.io.Serializable {

	private int roleId;
	private String role;
	private Set<Permissions> permissionses = new HashSet<Permissions>(0);
	private Set<User> userses = new HashSet<User>(0);

	public Role() {
	}

	public Role(int roleId, String role) {
		this.roleId = roleId;
		this.role = role;
	}

	public Role(int roleId, String role, Set<Permissions> permissionses, Set<User> userses) {
		this.roleId = roleId;
		this.role = role;
		this.permissionses = permissionses;
		this.userses = userses;
	}

	@Id

	@Column(name = "roleId", unique = true, nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role", nullable = false, length = 50)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "roles_permissions", catalog = "demo", joinColumns = {
			@JoinColumn(name = "roleId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "permissionId", nullable = false, updatable = false) })
	public Set<Permissions> getPermissionses() {
		return this.permissionses;
	}

	public void setPermissionses(Set<Permissions> permissionses) {
		this.permissionses = permissionses;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "roleses")
	public Set<User> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<User> userses) {
		this.userses = userses;
	}

}
